**IMPORT PANDAS**

In [1]:
import pandas as pd

**IMPORT EXCEL FILE THROUGH RELATIVE PATHING**

In [2]:
file_path = "../data/processed/uk_rents_jun_2026.xlsx"

**CREATE DATAFRAME**

In [3]:
df_jun_2026 = pd.read_excel(file_path, sheet_name='jun_26')

df_jun_2026.head(2)

,Time period,Area code,Area name,Region or country name,Index,Monthly change,Annual change,Rental price,Index one bed,Monthly change one bed,...,Annual change semidetached,Rental price semidetached,Index terraced,Monthly change terraced,Annual change terraced,Rental price terraced,Index flat maisonette,Monthly change flat maisonette,Annual change flat maisonette,Rental price flat maisonette
0,2026-06-01,K02000001,United Kingdom,[z],123.878836,0.307738,3.273026,1388,126.000163,0.338766,...,3.675366,1381,123.762362,0.289005,3.772354,1375,124.900311,0.288688,2.80896,1355
1,2026-06-01,K03000001,Great Britain,[z],123.87718,0.31358,3.296166,1400,126.019745,0.340866,...,3.717123,1399,123.691367,0.294092,3.795252,1391,124.938928,0.295406,2.831806,1361

**SLICE ONLY RENTAL PRICES, DO NOT INCLUDE INDICES NOR CHANGE RATES (WHETHER ANNUAL OR MONTHLY)**

In [4]:
df_prices = df_jun_2026.loc[:, ["Time period", "Area code", "Area name", 
                                "Region or country name", "Rental price", "Rental price one bed",
                                "Rental price two bed", "Rental price three bed", "Rental price four or more bed",
                                "Rental price detached", "Rental price semidetached", "Rental price terraced",
                                "Rental price flat maisonette"]]

df_prices.head(2)

,Time period,Area code,Area name,Region or country name,Rental price,Rental price one bed,Rental price two bed,Rental price three bed,Rental price four or more bed,Rental price detached,Rental price semidetached,Rental price terraced,Rental price flat maisonette
0,2026-06-01,K02000001,United Kingdom,[z],1388,1127,1270,1418,2061,1577,1381,1375,1355
1,2026-06-01,K03000001,Great Britain,[z],1400,1129,1279,1441,2098,1595,1399,1391,1361

**NORTHERN IRELAND BOOLEAN MASK (In order to effectively verify that NI has not data)**

In [5]:
df_prices[df_prices['Region or country name'] == 'Northern Ireland']

,Time period,Area code,Area name,Region or country name,Rental price,Rental price one bed,Rental price two bed,Rental price three bed,Rental price four or more bed,Rental price detached,Rental price semidetached,Rental price terraced,Rental price flat maisonette
349,2026-06-01,[z],Belfast BRMA,Northern Ireland,[x],[x],[x],[x],[x],[x],[x],[x],[x]
350,2026-06-01,[z],Lough Neagh Lower BRMA,Northern Ireland,[x],[x],[x],[x],[x],[x],[x],[x],[x]
351,2026-06-01,[z],Lough Neagh Upper BRMA,Northern Ireland,[x],[x],[x],[x],[x],[x],[x],[x],[x]
352,2026-06-01,[z],North Northern Ireland BRMA,Northern Ireland,[x],[x],[x],[x],[x],[x],[x],[x],[x]
353,2026-06-01,[z],North West Northern Ireland BRMA,Northern Ireland,[x],[x],[x],[x],[x],[x],[x],[x],[x]
354,2026-06-01,[z],South East Northern Ireland BRMA,Northern Ireland,[x],[x],[x],[x],[x],[x],[x],[x],[x]
355,2026-06-01,[z],South Northern Ireland BRMA,Northern Ireland,[x],[x],[x],[x],[x],[x],[x],[x],[x]
356,2026-06-01,[z],South West Northern Ireland BRMA,Northern Ireland,[x],[x],[x],[x],[x],[x],[x],[x],[x]

**SLICE NORTHERN IRELAND OFF, AND TEST IF THE SLICE WENT WELL WITH THE TAIL METHOD (THE LAST ENTRIES SHOULD SHOW "WALES")**

In [6]:
df_prices = df_prices.loc[df_prices['Region or country name'] != 'Northern Ireland', :]

df_prices.tail(2)

,Time period,Area code,Area name,Region or country name,Rental price,Rental price one bed,Rental price two bed,Rental price three bed,Rental price four or more bed,Rental price detached,Rental price semidetached,Rental price terraced,Rental price flat maisonette
347,2026-06-01,W06000023,Powys,Wales,621,461,578,699,952,799,663,610,486
348,2026-06-01,W06000024,Merthyr Tydfil,Wales,754,552,640,722,1091,1084,765,684,602

**EXPORT**

In [7]:
excel_path = "../data/processed/uk_rents_jun_2026.xlsx"

with pd.ExcelWriter(
    excel_path,
    engine='openpyxl',
    mode='a',
    if_sheet_exists='replace',
) as writer:

    df_prices.to_excel(writer, sheet_name='prices', index=False)